name: Latest Medium story workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Medium post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mahmutgemici0/blog-post-workflow@main
        with:
          comment_tag_name: "MEDIUM-STORY-LIST"
          feed_list: "https://medium.com/feed/@mahmutgemici7"